### ISSUE TITLE
Long Range Targeting listed as unknown category

### ISSUE THREAD

**Issue by nyllet2** [whinis/eve-jacknife#10]
As the title say, the skill Long range targeting is listed as "Unknown category" in the skills section, other then that, really great tool!

**Comment by whinis** [comment]
Is this on your own install or at evejackknife.com ?

**Comment by nyllet2** [comment]
It's on my own install, I noticed I was using a dated version, however after updating to the last version all skills are listed as "Unknown category"
![image](https://cloud.githubusercontent.com/assets/8387269/12126481/bec2548e-b3f1-11e5-834a-0958f9192ed3.png)

Might be some DB issue, I'll try reinstalling and see what happens

**Comment by whinis** [comment]
That means that you havn't updated your database, just run the updater

EDIT:
The updater can be accessed by just going to {url}/Installer.php and if you have a full install should show you a updater.

**Comment by nyllet2** [comment]
Noticed there was something missing so I ran the installer again, this time when running update.php I got the following error message
![image](https://cloud.githubusercontent.com/assets/8387269/12126606/80ded2b8-b3f2-11e5-828e-1a5ead4c52c8.png)

**Comment by whinis** [comment]
Can you try using Installer.php, update.php may not be updated for some small changes in the dump file.

**Comment by nyllet2** [comment]
Done, the installer display the following; 
![image](https://cloud.githubusercontent.com/assets/8387269/12126706/15214802-b3f3-11e5-8239-29ac1d07c80f.png)

However, when I now go to the main page, I get the following;
![image](https://cloud.githubusercontent.com/assets/8387269/12126747/491ec9b8-b3f3-11e5-82b2-944446f325e8.png)

If I reload the page, it loads and I can run an API check, however it still return the same error every few times I change the "view"

**Comment by whinis** [comment]
That's extremely odd, That suggest that eveApi.Base.php doesn't exist on your install. It should be in the eveApi folder. However without that none of the apis should work.

**Comment by nyllet2** [comment]
eveAPI.Base.php are located in the folder on the FTP server when looking there
![image](https://cloud.githubusercontent.com/assets/8387269/12126854/11f2a990-b3f4-11e5-8494-3419fad3f585.png)

**Comment by whinis** [comment]
Could you try eve.php from the latest push and see if that solves your problem ?

**Comment by nyllet2** [comment]
That seems to have done the trick! No crashes during my ultra-rapid monkeytesting :)

Thanks for doing an awesome job!
