### ISSUE TITLE
(low) warning "Couldn't fetch mysqli_stmt"

### ISSUE THREAD

**Issue by nyllet2** [whinis/eve-jacknife#11]
When using an API key which have more then a single character on the account, you get the following warning:
![image](https://cloud.githubusercontent.com/assets/8387269/12140599/953def56-b469-11e5-8fca-7a79f6c48626.png)

**Comment by whinis** [comment]
I have actually pushed a fix for that as well, the latest branch shouldn't have that problem anymore :D

**Comment by nyllet2** [comment]
Perfect, seems to be working properly now! great work!
