### ISSUE TITLE
(low) Warning: "mysqli_affected_rows()~" when registering a new account

### ISSUE THREAD

**Issue by nyllet2** [whinis/eve-jacknife#12]
When registering a new account (when allow_login is set to 'True' in eve.config.php you get the following error message, the account is however still created.
![image](https://cloud.githubusercontent.com/assets/8387269/12147172/dc203b08-b497-11e5-9a3f-a7a6139eb11d.png)

**Comment by whinis** [comment]
Does that fix this issue ?
