### ISSUE TITLE
Errors when viewing kills or transactions.

### ISSUE THREAD

**Issue by PerMalmberg** [whinis/eve-jacknife#14]
We've got an application with an API that gives the following error when viewing either kills or transactions, any idea what's going on?

<pre>
PHP Notice:  Trying to get property of non-object in 
/jackknife/eveApi/eveApi.base.php on line 71, referer: /jackknife/index.php?chid=881003936&usid=111111&apik=222222222&save=1&small

PHP Fatal error:  Call to a member function xpath() on a non-object in /jackknife/eveApi/eveApiCharacterAffiliations.class.php on line 36, referer: /jackknife/index.php?chid=881003936&usid=1111111&apik=2222222&save=1&small
</pre>

Br,

Per

**Comment by whinis** [comment]
So, that error seems to suggest that it can't find either a corp, alliance, or player that is on the killmail or transaction which is odd because none-should have been deleted from eve.

**Comment by PerMalmberg** [comment]
Ok, what can I do to help track it down?

**Comment by whinis** [comment]
Ill put in code to check for the error as there is nothing I can realistically do about a player that has disappeared.

**Comment by PerMalmberg** [comment]
True that.

Will you just skip the entry or print "unknown" (or similar) instead?

**Comment by whinis** [comment]
ill add Unknown (player/corp/alliance)

**Comment by PerMalmberg** [comment]
Very good. Thanks for the quick replies.

**Comment by markus-lassfolk** [comment]
I've just installed the latest version (git clone) and I'm also experiencing this issue.

**Comment by whinis** [comment]
@markus-lassfolk Could you try that and see if it gives you a new error now? I am having trouble finding an api that is actually generating this error.

**Comment by markus-lassfolk** [comment]
Please send me a mail to markus at lassfolk dot net 
and i will give you a key that works

**Comment by markus-lassfolk** [comment]
Sent a key to you on bitbucket where i could send a pm

**Comment by whinis** [comment]
Alright, I just committed something that should fix the problem. It occurred whenever I attempted to ask ccp about more than 250 characters/alliances/corps. The api only allows 250 so returned an error and broke things. It should now chunk the asked characters into 250 at a time.
