### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by PerMalmberg** [whinis/eve-jacknife#15]
Here's two requests from our recruiters:
- Show corp history for the character
- An easy way to copy all asset-texts (for all locations) so that it can be fed to evepraisal.com.

Thoughts?

**Comment by whinis** [comment]
I will look into the first one as it makes sense
The second one sounds like an amazing idea that I will implement in the coming weeks

**Comment by PerMalmberg** [comment]
Awesome, our recruiters will love you for this.

**Comment by whinis** [comment]
Alright, the current master branch should contain both the evepraisal modal as well as a corp history modal.

**Comment by PerMalmberg** [comment]
Sweet, will update asap.

**Comment by PerMalmberg** [comment]
Good job. The corp history could be made easier to find though, such as a "(history)" link after the corp name instead. Also, how about adding some space between the links at the top of the pages, that'll make them easier to find and read.

Something small I noticed: We got a new member today that is still listed as a member of the NPC corp. Clicking the NPC corp-name shows the correct history, including our corp. Cache issue?

**Comment by whinis** [comment]
Likely a cache issue due to corp history being from a different endpoint than the other character information. 

I can easily change that to a history link, but what do you mean by the links at the top of the page? the ones that go to specific pages ?

**Comment by PerMalmberg** [comment]
Yeah, the "skills, assets, bookmarks" etc. Adding a little space between them would make it easier on the eyes imho.

**Comment by PerMalmberg** [comment]
Somewhat related, how do you make Jackknife update the data? Got "updated 9 days, 5 hours, 2 minutes, 9 seconds ago" on the skills page. that's quite a long time.

**Comment by whinis** [comment]
It should be updating automatically, let me check whats going on

**Comment by whinis** [comment]
Alright, that should fix it. I need to put out an announcement due to it not deleteing cached results
thank you

**Comment by PerMalmberg** [comment]
Much better! Thank you!
