### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by epoch18** [whinis/eve-jacknife#17]
Any notes for installation? Server requirements/dependencies?
Thanks!

**Comment by epoch18** [comment]
Sorry. I forgot closed issues aren't shown by default. I'll do some more looking.

**Comment by epoch18** [comment]
Ok yes, a list of dependencies would be great, please.

**Comment by whinis** [comment]
I will add this to the readme, but it basically needs a MySql Server, a Php server, and a Web Server. Apache, Lighttpd, and nginx have all been confirmed to work along with mod_php and php-fpm. I have not yet tested on php 7 however.

**Comment by epoch18** [comment]
Well then I guess I'll let you know how it goes with php7. :)

**Comment by whinis** [comment]
Any changes that need to be made for php 7 I am happy to make, so let me know how it goes.
