### ISSUE TITLE
Corp API's

### ISSUE THREAD

**Issue by ppfeufer** [whinis/eve-jacknife#19]
Hey there,

it seems that corp API's are not working at all. Any chance of getting this fixed?

**Comment by whinis** [comment]
Let me look into the issue. is there any particular error ?

**Comment by ppfeufer** [comment]
HTTP ERROR 500 which does not say much at all, but seems to be an issue with the API endpoint if I would have a wild guess, since account API work just fine. Your demo site at http://evejackknife.com/ has the same issue, so it's not only in our installation.

**Comment by whinis** [comment]
Alright, let me see if I can figure out whats going on here. No telling with CCP

**Comment by whinis** [comment]
Can you confirm if that push fixes the issue ?

**Comment by ppfeufer** [comment]
Yep, confirmed, works now.

Thank your for the quick fix!
