### ISSUE TITLE
Error during Install Routine

### ISSUE THREAD

**Issue by ppfeufer** [whinis/eve-jacknife#2]
Browsing to the Installer.php and filling out the DB credential needed. After clicking "save" following error encounters:

Fatal error: Call to a member function fetch_array() on a non-object in Installer.php on line 111 

Doing all the config stuff manually, also doing the DB manually works thou ....

**Comment by whinis** [comment]
Could I get some information about where you have this installed? php version and do you have mysqlnd driver installed ?

**Comment by ppfeufer** [comment]
I'm running: 

MySQL
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.0.22-MariaDB-log - Source distribution

Webserver
Apache 2.2.31
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $

PHP version 5.5.30

**Comment by whinis** [comment]
Thank you, let me see whats going on a similar environment

**Comment by whinis** [comment]
Could you try that latest push and tell me what error it gives you ?

**Comment by ppfeufer** [comment]
I do not get boynd the "Check" state. It doesn't even do the Database Check any longer now.
![screenie_013](https://cloud.githubusercontent.com/assets/2989985/11911337/83687e68-a613-11e5-834d-4de429a94dcb.png)

**Comment by ppfeufer** [comment]
Ah ignore what I said, it didn't write the config file properly.

Notice: (SQL)You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-jacknife' at line 1 query: SHOW TABLES FROM eve-jacknife in Installer.php on line 112

Fatal error: Call to a member function fetch_array() on a non-object in Installer.php on line 114

Looks like it's struggling with the table name ....

**Comment by ppfeufer** [comment]
Yes, after testing another name for the database, it's working. So database names with an '-' are not working.

**Comment by whinis** [comment]
Alright, try my latest installer and see if that fixes it, Note that it will attempt to edit the config file if you have one because I moved a constant to that file.
