### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by tim7433** [whinis/eve-jacknife#22]
I got the site to the initial landing page but I'm unable to process any of the APIs that are entered. It returns an HTTP ERROR 500.

**Comment by whinis** [comment]
I just checked and didn't see any 500 errors in my logs and it loaded perfect fine on my side, are you still having the issue?

**Comment by tim7433** [comment]
It's my local instance of it. Not the main instance.

**Comment by whinis** [comment]
Do you see any errors in your nginx/apache/lighttpd log that would explain the 500 error? Its difficult to diagnose only with a 500 error

**Comment by tim7433** [comment]
Apache

[Mon Jul 31 17:44:51.553468 2017] [:error] [pid 2775] [client xxx.xx.xxx.xx:xxxxx] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/eve-jacknife-master/eveApi/eveApiCaching.php:146\nStack trace:\n#0 /var/www/html/eve-jacknife-master/index.php(153): cache_api_retrieve(Object(eveDb), '/account/APIKey...', Array, 300)\n#1 {main}\n  thrown in /var/www/html/eve-jacknife-master/eveApi/eveApiCaching.php on line 146, referer: https://jacknife.chasek.tech/eve-jacknife-master/

**Comment by tim7433** [comment]
https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init
