### ISSUE TITLE
Parameter mismatch on mysqli_bind

### ISSUE THREAD

**Issue by ppfeufer** [whinis/eve-jacknife#3]
This occures on the "At a glace" page when scrolling a bit down. between "Orders" and "Contacts". The line shows up multiple time.

Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in class_db.php on line 127

![screenie_012](https://cloud.githubusercontent.com/assets/2989985/11910831/ab5256e0-a601-11e5-87f2-16da0caaeef1.png)

**Comment by whinis** [comment]
I just pushed something that should fix that problem

**Comment by ppfeufer** [comment]
Yes, that fixed it.
