### ISSUE TITLE
[Feature Request] Open Mail "smoother" for better User Experience

### ISSUE THREAD

**Issue by ppfeufer** [whinis/eve-jacknife#4]
Sorry for firing all this stuff in one night, but I am just testing all this stuff.

At the moment if I'm going to read a mail from the API, the mail opens as a new site. Would be more friendly to open it the same way the contracts are opening. Those are shown below their haderline on click, also closing them is possible. Would be nice to have that for the mails as well, instead loading them as a new page from which you have to get back to the overview.

Thank you

**Comment by whinis** [comment]
While, its not quite as easy as contracts, I can easily see me doing this in a ajax call. Let me see what I can do there.

**Comment by whinis** [comment]
Alright, the latest push should allow you to read inline messages

**Comment by ppfeufer** [comment]
Yep works so far. Thank you for the fast fix :-)

Is it possible to strip the HTML code from the mail?
Some of them - the formatted ones - are pretty awe full when displayed. I think it is, because CCP is formatting every line with a font-size attribute as well, which makes not that much sense.

![screenie_014](https://cloud.githubusercontent.com/assets/2989985/11911480/c91664b8-a616-11e5-8247-589bfa68e787.png)

**Comment by whinis** [comment]
I am trying to figure out the best way to handle it. While stripping it makes it easier to read it might remove something from the mail. Going to sleep on the best way to handle this.

**Comment by whinis** [comment]
Alright, I have added a button at the top of the mail page to toggle between formatting being on or off.
